In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("pp-2022.csv",header=None)

In [3]:
df.set_axis(['Transaction unique identifier','Price','Date of Transfer','Postcode','Property Type','Old/New','Duration',
             'PAON','SAON','Street','Locality','Town/City','District','County','PPD Category Type','Record Status'], 
            axis='columns', inplace=True)

In [4]:
lst_columns=['Postcode','Property Type','Old/New','Duration',
             'PAON','SAON','Street','Locality','Town/City','District','County','PPD Category Type','Record Status']

In [5]:
for i in lst_columns:
    df[i] = df[i].astype(pd.StringDtype())

In [20]:
df.head()

,Transaction unique identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status,House_Unique
0,{DBA933FA-5665-669D-E053-6B04A8C0AD56},232999,2022-01-27 00:00,HU15 1FT,F,N,L,FAIRWAY VIEW,APARTMENT 27,ELLOUGHTON ROAD,,BROUGH,EAST RIDING OF YORKSHIRE,EAST RIDING OF YORKSHIRE,A,A,FAIRWAY VIEW APARTMENT 27 ELLOUGHTON ROAD
1,{DBA933FA-5666-669D-E053-6B04A8C0AD56},367250,2022-02-25 00:00,HU17 9RT,D,N,F,"ASHCROFT, 216",,HULL BRIDGE ROAD,,BEVERLEY,EAST RIDING OF YORKSHIRE,EAST RIDING OF YORKSHIRE,A,A,"ASHCROFT, 216 HULL BRIDGE ROAD"
2,{DBA933FA-5668-669D-E053-6B04A8C0AD56},425000,2022-02-18 00:00,HU14 3EZ,D,N,F,4,,PARKLANDS CRESCENT,,NORTH FERRIBY,EAST RIDING OF YORKSHIRE,EAST RIDING OF YORKSHIRE,A,A,4 PARKLANDS CRESCENT
3,{DBA933FA-566B-669D-E053-6B04A8C0AD56},217000,2022-02-18 00:00,DN14 7ZL,S,N,F,59,,LANGHORN DRIVE,HOWDEN,GOOLE,EAST RIDING OF YORKSHIRE,EAST RIDING OF YORKSHIRE,A,A,59 LANGHORN DRIVE HOWDEN
4,{DBA933FA-566E-669D-E053-6B04A8C0AD56},189950,2022-01-31 00:00,YO16 6AE,D,N,F,6,,ALDERSHOT DRIVE,,BRIDLINGTON,EAST RIDING OF YORKSHIRE,EAST RIDING OF YORKSHIRE,A,A,6 ALDERSHOT DRIVE

In [34]:
df.iloc[4,:]

Transaction unique identifier    {DBA933FA-566E-669D-E053-6B04A8C0AD56}
Price                                                            189950
Date of Transfer                                       2022-01-31 00:00
Postcode                                                       YO16 6AE
Property Type                                                         D
Old/New                                                               N
Duration                                                              F
PAON                                                                  6
SAON
Street                                                  ALDERSHOT DRIVE
Locality
Town/City                                                   BRIDLINGTON
District                                       EAST RIDING OF YORKSHIRE
County                                         EAST RIDING OF YORKSHIRE
PPD Category Type                                                     A
Record Status                                                         A
House_Unique                                        6  ALDERSHOT DRIVE
Name: 4, dtype: object

In [30]:
a=df["Town/City"].unique()
b=sorted(a)
b[50:]

['BALA',
 'BALDOCK',
 'BAMBURGH',
 'BAMPTON',
 'BANBURY',
 'BANGOR',
 'BANSTEAD',
 'BANWELL',
 'BARGOED',
 'BARKING',
 'BARMOUTH',
 'BARNARD CASTLE',
 'BARNET',
 'BARNETBY',
 'BARNOLDSWICK',
 'BARNSLEY',
 'BARNSTAPLE',
 'BARROW-IN-FURNESS',
 'BARROW-UPON-HUMBER',
 'BARRY',
 'BARTON-UPON-HUMBER',
 'BASILDON',
 'BASINGSTOKE',
 'BATH',
 'BATLEY',
 'BATTLE',
 'BEACONSFIELD',
 'BEAMINSTER',
 'BEAUMARIS',
 'BEAWORTHY',
 'BECCLES',
 'BECKENHAM',
 'BECKERMET',
 'BEDALE',
 'BEDFORD',
 'BEDLINGTON',
 'BEDWORTH',
 'BELFORD',
 'BELPER',
 'BELVEDERE',
 'BEMBRIDGE',
 'BENFLEET',
 'BERKELEY',
 'BERKHAMSTED',
 'BERWICK-UPON-TWEED',
 'BETCHWORTH',
 'BETWS-Y-COED',
 'BEVERLEY',
 'BEWDLEY',
 'BEXHILL-ON-SEA',
 'BEXLEY',
 'BEXLEYHEATH',
 'BICESTER',
 'BIDEFORD',
 'BIGGLESWADE',
 'BILLERICAY',
 'BILLINGHAM',
 'BILLINGSHURST',
 'BILSTON',
 'BINGLEY',
 'BIRCHINGTON',
 'BIRKENHEAD',
 'BIRMINGHAM',
 'BISHOP AUCKLAND',
 "BISHOP'S STORTFORD",
 'BISHOPS CASTLE',
 'BLACKBURN',
 'BLACKPOOL',
 'BLACKWOOD',
 'BLAENAU FFESTINIOG',
 'BLAKENEY',
 'BLANDFORD FORUM',
 'BLAYDON-ON-TYNE',
 'BLYTH',
 'BODMIN',
 'BODORGAN',
 'BOGNOR REGIS',
 'BOLDON COLLIERY',
 'BOLTON',
 'BONCATH',
 'BOOTLE',
 'BORDON',
 'BOREHAMWOOD',
 'BORTH',
 'BOSCASTLE',
 'BOSTON',
 'BOURNE',
 'BOURNE END',
 'BOURNEMOUTH',
 'BOW STREET',
 'BRACKLEY',
 'BRACKNELL',
 'BRADFORD',
 'BRADFORD-ON-AVON',
 'BRAINTREE',
 'BRAMPTON',
 'BRANDON',
 'BRAUNTON',
 'BRECON',
 'BRENTFORD',
 'BRENTWOOD',
 'BRIDGEND',
 'BRIDGNORTH',
 'BRIDGWATER',
 'BRIDLINGTON',
 'BRIDPORT',
 'BRIERLEY HILL',
 'BRIGG',
 'BRIGHOUSE',
 'BRIGHTON',
 'BRISTOL',
 'BRIXHAM',
 'BROADSTAIRS',
 'BROADSTONE',
 'BROADWAY',
 'BROCKENHURST',
 'BROMLEY',
 'BROMSGROVE',
 'BROMYARD',
 'BROSELEY',
 'BROUGH',
 'BROUGHTON-IN-FURNESS',
 'BROXBOURNE',
 'BRUTON',
 'BRYNTEG',
 'BUCKFASTLEIGH',
 'BUCKHURST HILL',
 'BUCKINGHAM',
 'BUCKLEY',
 'BUCKNELL',
 'BUDE',
 'BUDLEIGH SALTERTON',
 'BUILTH WELLS',
 'BUNGAY',
 'BUNTINGFORD',
 'BURES',
 'BURFORD',
 'BURGESS HILL',
 'BURNHAM-ON-CROUCH',
 'BURNHAM-ON-SEA',
 'BURNLEY',
 'BURNTWOOD',
 'BURRY PORT',
 'BURTON-ON-TRENT',
 'BURY',
 'BURY ST EDMUNDS',
 'BUSHEY',
 'BUXTON',
 'CAERNARFON',
 'CAERPHILLY',
 'CAERSWS',
 'CALDICOT',
 'CALLINGTON',
 'CALNE',
 'CALSTOCK',
 'CAMBERLEY',
 'CAMBORNE',
 'CAMBRIDGE',
 'CAMELFORD',
 'CANNOCK',
 'CANTERBURY',
 'CANVEY ISLAND',
 'CARDIFF',
 'CARDIGAN',
 'CARLISLE',
 'CARMARTHEN',
 'CARNFORTH',
 'CARSHALTON',
 'CARTERTON',
 'CASTLE CARY',
 'CASTLEFORD',
 'CATERHAM',
 'CATTERICK GARRISON',
 'CEMAES BAY',
 'CHALFONT ST GILES',
 'CHARD',
 'CHATHAM',
 'CHATHILL',
 'CHATTERIS',
 'CHEADLE',
 'CHEDDAR',
 'CHELMSFORD',
 'CHELTENHAM',
 'CHEPSTOW',
 'CHERTSEY',
 'CHESHAM',
 'CHESSINGTON',
 'CHESTER',
 'CHESTER LE STREET',
 'CHESTERFIELD',
 'CHICHESTER',
 'CHIGWELL',
 'CHINNOR',
 'CHIPPENHAM',
 'CHIPPING CAMPDEN',
 'CHIPPING NORTON',
 'CHISLEHURST',
 'CHOPPINGTON',
 'CHORLEY',
 'CHRISTCHURCH',
 'CHULMLEIGH',
 'CHURCH STRETTON',
 'CINDERFORD',
 'CIRENCESTER',
 'CLACTON-ON-SEA',
 'CLARBESTON ROAD',
 'CLEATOR',
 'CLEATOR MOOR',
 'CLECKHEATON',
 'CLEETHORPES',
 'CLEVEDON',
 'CLITHEROE',
 'CLYNDERWEN',
 'COALVILLE',
 'COBHAM',
 'COCKERMOUTH',
 'COLCHESTER',
 'COLEFORD',
 'COLNE',
 'COLWYN BAY',
 'COLYTON',
 'CONGLETON',
 'CONISTON',
 'CONSETT',
 'CONWY',
 'CORBRIDGE',
 'CORBY',
 'CORNHILL-ON-TWEED',
 'CORSHAM',
 'CORWEN',
 'COTTINGHAM',
 'COULSDON',
 'COVENTRY',
 'COWBRIDGE',
 'COWES',
 'CRADLEY HEATH',
 'CRAMLINGTON',
 'CRANBROOK',
 'CRANLEIGH',
 'CRAVEN ARMS',
 'CRAWLEY',
 'CREDITON',
 'CREWE',
 'CREWKERNE',
 'CRICCIETH',
 'CRICKHOWELL',
 'CROMER',
 'CROOK',
 'CROWBOROUGH',
 'CROWTHORNE',
 'CROYDON',
 'CRYMYCH',
 'CULLOMPTON',
 'CWMBRAN',
 'DAGENHAM',
 'DALTON-IN-FURNESS',
 'DARLINGTON',
 'DARTFORD',
 'DARTMOUTH',
 'DARWEN',
 'DAVENTRY',
 'DAWLISH',
 'DEAL',
 'DEESIDE',
 'DELABOLE',
 'DENBIGH',
 'DERBY',
 'DEREHAM',
 'DEVIZES',
 'DEWSBURY',
 'DIDCOT',
 'DINAS POWYS',
 'DISS',
 'DOLGELLAU',
 'DOLWYDDELAN',
 'DONCASTER',
 'DORCHESTER',
 'DORKING',
 'DOVER',
 'DOWNHAM MARKET',
 'DRIFFIELD',
 'DROITWICH',
 'DRONFIELD',
 'DRYBROOK',
 'DUDLEY',
 'DUKINFIELD',
 'DULVERTON',
 'DUNMOW',
 'DUNSTABLE',
 'DURHAM',
 'DURSLEY',
 'DYFFRYN ARDUDWY',
 'DYMOCK',
 'EAST BOLDON',
 'EAST COWES',
 'EAST GRINSTEAD',
 'EAST MOLESEY',
 'EASTBOURNE',
 'EASTLEIGH',
 'EBBW VALE',
 'EDENBRIDGE',
 'EDGWARE',
 'EGHAM',
 'EGREMONT',
 'ELLAND',
 'ELLESMERE',
 'ELLESMERE PORT',
 'ELY',
 'EMSWORTH',
 'ENFIELD',
 'EPPING',
 'EPSOM',
 'ERITH',
 'ESHER',
 'ETCHINGHAM',
 'EVESHAM',
 'EXETER',
 'EXMOUTH',
 'EYE',
 'FAIRBOURNE',
 'FAIRFORD',
 'FAKENHAM',
 'FALMOUTH',
 'FAREHAM',
 'FARINGDON',
 'FARNBOROUGH',
 'FARNHAM',
 'FAVERSHAM',
 'FELIXSTOWE',
 'FELTHAM',
 'FERNDALE',
 'FERNDOWN',
 'FERRYHILL',
 'FERRYSIDE',
 'FILEY',
 'FISHGUARD',
 'FLEET',
 'FLEETWOOD',
 'FLINT',
 'FOLKESTONE',
 'FORDINGBRIDGE',
 'FOREST ROW',
 'FOWEY',
 'FRESHWATER',
 'FRINTON-ON-SEA',
 'FRIZINGTON',
 'FRODSHAM',
 'FROME',
 'GAERWEN',
 'GAINSBOROUGH',
 'GARNDOLBENMAEN',
 'GATESHEAD',
 'GERRARDS CROSS',
 'GILLINGHAM',
 'GLASTONBURY',
 'GLOGUE',
 'GLOSSOP',
 'GLOUCESTER',
 'GODALMING',
 'GODSTONE',
 'GOODWICK',
 'GOOLE',
 'GOSPORT',
 'GRANGE-OVER-SANDS',
 'GRANTHAM',
 'GRAVESEND',
 'GRAYS',
 'GREAT MISSENDEN',
 'GREAT YARMOUTH',
 'GREENFORD',
 'GREENHITHE',
 'GRIMSBY',
 'GUILDFORD',
 'GUISBOROUGH',
 'GUNNISLAKE',
 'HAILSHAM',
 'HALESOWEN',
 'HALESWORTH',
 'HALIFAX',
 'HALSTEAD',
 'HALTWHISTLE',
 'HAMPTON',
 'HARLECH',
 'HARLESTON',
 'HARLOW',
 'HARPENDEN',
 'HARROGATE',
 'HARROW',
 'HARTFIELD',
 'HARTLEPOOL',
 'HARWICH',
 'HASLEMERE',
 'HASSOCKS',
 'HASTINGS',
 'HATFIELD',
 'HAVANT',
 'HAVERFORDWEST',
 'HAVERHILL',
 'HAWES',
 'HAYES',
 'HAYLE',
 'HAYLING ISLAND',
 'HAYWARDS HEATH',
 'HEANOR',
 'HEATHFIELD',
 'HEBBURN',
 'HEBDEN BRIDGE',
 'HECKMONDWIKE',
 'HELSTON',
 'HEMEL HEMPSTEAD',
 'HENFIELD',
 'HENGOED',
 'HENLEY-IN-ARDEN',
 'HENLEY-ON-THAMES',
 'HENLOW',
 'HEREFORD',
 'HERNE BAY',
 'HERTFORD',
 'HESSLE',
 'HEXHAM',
 'HEYWOOD',
 'HIGH PEAK',
 'HIGH WYCOMBE',
 'HIGHBRIDGE',
 'HINCKLEY',
 'HINDHEAD',
 'HINTON ST GEORGE',
 'HITCHIN',
 'HOCKLEY',
 'HODDESDON',
 'HOLMFIRTH',
 'HOLMROOK',
 'HOLSWORTHY',
 'HOLT',
 'HOLYHEAD',
 'HOLYWELL',
 'HONITON',
 'HOOK',
 'HOPE VALLEY',
 'HORLEY',
 'HORNCASTLE',
 'HORNCHURCH',
 'HORNSEA',
 'HORSHAM',
 'HOUGHTON LE SPRING',
 'HOUNSLOW',
 'HOVE',
 'HUDDERSFIELD',
 'HULL',
 'HUNGERFORD',
 'HUNSTANTON',
 'HUNTINGDON',
 'HYDE',
 'HYTHE',
 'IBSTOCK',
 'ILFORD',
 'ILFRACOMBE',
 'ILKESTON',
 'ILKLEY',
 'ILMINSTER',
 'IMMINGHAM',
 'INGATESTONE',
 'IPSWICH',
 'ISLES OF SCILLY',
 'ISLEWORTH',
 'IVER',
 'IVYBRIDGE',
 'JARROW',
 'KEIGHLEY',
 'KENDAL',
 'KENILWORTH',
 'KENLEY',
 'KESTON',
 'KESWICK',
 'KETTERING',
 'KIDDERMINSTER',
 'KIDLINGTON',
 'KIDWELLY',
 'KILGETTY',
 "KING'S LYNN",
 'KINGS LANGLEY',
 'KINGSBRIDGE',
 'KINGSTON UPON THAMES',
 'KINGSWINFORD',
 'KINGTON',
 'KIRKBY STEPHEN',
 'KIRKBY-IN-FURNESS',
 'KNARESBOROUGH',
 'KNEBWORTH',
 'KNIGHTON',
 'KNOTTINGLEY',
 'KNUTSFORD',
 'LAMPETER',
 'LANCASTER',
 'LANCING',
 'LANGPORT',
 'LAUNCESTON',
 'LEAMINGTON SPA',
 'LEATHERHEAD',
 'LECHLADE',
 'LEDBURY',
 'LEE-ON-THE-SOLENT',
 'LEEDS',
 'LEEK',
 'LEICESTER',
 'LEIGH',
 'LEIGH-ON-SEA',
 'LEIGHTON BUZZARD',
 'LEISTON',
 'LEOMINSTER',
 'LETCHWORTH GARDEN CITY',
 'LEWES',
 'LEYBURN',
 'LEYLAND',
 'LICHFIELD',
 'LIFTON',
 'LIGHTWATER',
 'LINCOLN',
 'LINGFIELD',
 'LIPHOOK',
 'LISKEARD',
 'LISS',
 'LITTLEBOROUGH',
 'LITTLEHAMPTON',
 'LIVERPOOL',
 'LIVERSEDGE',
 'LLANARTH',
 'LLANBEDR',
 'LLANBEDRGOCH',
 'LLANBRYNMAIR',
 'LLANDEILO',
 'LLANDINAM',
 'LLANDOVERY',
 'LLANDRINDOD WELLS',
 'LLANDUDNO',
 'LLANDUDNO JUNCTION',
 'LLANDYSUL',
 'LLANELLI',
 'LLANFAIRFECHAN',
 'LLANFAIRPWLLGWYNGYLL',
 'LLANFECHAIN',
 'LLANFYLLIN',
 'LLANFYRNACH',
 'LLANGADOG',
 'LLANGAMMARCH WELLS',
 'LLANGEFNI',
 'LLANGOLLEN',
 'LLANIDLOES',
 'LLANNERCH-Y-MEDD',
 'LLANON',
 'LLANRHYSTUD',
 'LLANRWST',
 'LLANSANTFFRAID',
 'LLANTWIT MAJOR',
 'LLANWRDA',
 'LLANWRTYD WELLS',
 'LLANYBYDDER',
 'LLANYMYNECH',
 'LLWYNGWRIL',
 'LONDON',
 'LONGFIELD',
 'LONGHOPE',
 'LOOE',
 'LOSTWITHIEL',
 'LOUGHBOROUGH',
 'LOUGHTON',
 'LOUTH',
 'LOWESTOFT',
 'LUDLOW',
 'LUTON',
 'LUTTERWORTH',
 'LYDBROOK',
 'LYDBURY NORTH',
 'LYDNEY',
 'LYME REGIS',
 'LYMINGTON',
 'LYMM',
 'LYNDHURST',
 'LYNMOUTH',
 'LYNTON',
 'LYTHAM ST ANNES',
 'MABLETHORPE',
 'MACCLESFIELD',
 'MACHYNLLETH',
 'MAESTEG',
 'MAIDENHEAD',
 'MAIDSTONE',
 'MALDON',
 'MALMESBURY',
 'MALPAS',
 'MALTON',
 'MALVERN',
 'MANCHESTER',
 'MANNINGTREE',
 'MANSFIELD',
 'MARAZION',
 'MARCH',
 'MARGATE',
 'MARKET DRAYTON',
 'MARKET HARBOROUGH',
 'MARKET RASEN',
 'MARKFIELD',
 'MARLBOROUGH',
 'MARLOW',
 'MARTOCK',
 'MARYPORT',
 'MATLOCK',
 'MAYFIELD',
 'MEIFOD',
 'MELKSHAM',
 'MELTON CONSTABLE',
 'MELTON MOWBRAY',
 'MENAI BRIDGE',
 'MERRIOTT',
 'MERTHYR TYDFIL',
 'MEXBOROUGH',
 'MIDDLESBROUGH',
 'MIDDLEWICH',
 'MIDHURST',
 'MILFORD HAVEN',
 'MILLOM',
 'MILNTHORPE',
 'MILTON KEYNES',
 'MINDRUM',
 'MINEHEAD',
 'MIRFIELD',
 'MITCHAM',
 'MITCHELDEAN',
 'MOELFRE',
 'MOLD',
 'MONMOUTH',
 'MONTACUTE',
 'MONTGOMERY',
 'MOOR ROW',
 'MORDEN',
 'MORECAMBE',
 'MORETON-IN-MARSH',
 'MORPETH',
 'MOUNTAIN ASH',
 'MUCH HADHAM',
 'MUCH WENLOCK',
 'NANTWICH',
 'NARBERTH',
 'NEATH',
 'NELSON',
 'NESTON',
 'NEW MALDEN',
 'NEW MILTON',
 'NEW QUAY',
 'NEW ROMNEY',
 'NEW TREDEGAR',
 'NEWARK',
 'NEWBIGGIN-BY-THE-SEA',
 'NEWBURY',
 'NEWCASTLE',
 'NEWCASTLE EMLYN',
 'NEWCASTLE UPON TYNE',
 'NEWCASTLETON',
 'NEWENT',
 'NEWHAVEN',
 'NEWMARKET',
 'NEWNHAM',
 'NEWPORT',
 'NEWPORT PAGNELL',
 'NEWQUAY',
 'NEWTON ABBOT',
 'NEWTON AYCLIFFE',
 'NEWTON-LE-WILLOWS',
 'NEWTOWN',
 'NORMANTON',
 'NORTH FERRIBY',
 'NORTH SHIELDS',
 'NORTH TAWTON',
 'NORTH WALSHAM',
 'NORTHALLERTON',
 'NORTHAMPTON',
 'NORTHOLT',
 'NORTHWICH',
 'NORTHWOOD',
 'NORWICH',
 'NOTTINGHAM',
 'NUNEATON',
 'OAKHAM',
 'OKEHAMPTON',
 'OLDBURY',
 'OLDHAM',
 'OLNEY',
 'ONGAR',
 'ORMSKIRK',
 'ORPINGTON',
 'OSSETT',
 'OSWESTRY',
 'OTLEY',
 'OTTERY ST MARY',
 'OXFORD',
 'OXTED',
 'PADSTOW',
 'PAIGNTON',
 'PAR',
 'PEACEHAVEN',
 'PEMBROKE',
 'PEMBROKE DOCK',
 'PENARTH',
 'PENCADER',
 'PENMAENMAWR',
 'PENRHYNDEUDRAETH',
 'PENRITH',
 'PENRYN',
 'PENTRAETH',
 'PENTRE',
 'PENYSARN',
 'PENZANCE',
 'PERRANPORTH',
 'PERSHORE',
 'PETERBOROUGH',
 'PETERLEE',
 'PETERSFIELD',
 'PETWORTH',
 'PEVENSEY',
 'PEWSEY',
 'PICKERING',
 'PINNER',
 'PLYMOUTH',
 'POLEGATE',
 'PONTEFRACT',
 'PONTYCLUN',
 'PONTYPOOL',
 'PONTYPRIDD',
 'POOLE',
 'PORT DINORWIC',
 'PORT ISAAC',
 'PORT TALBOT',
 'PORTH',
 'PORTHCAWL',
 'PORTHMADOG',
 'PORTLAND',
 'PORTSMOUTH',
 'POTTERS BAR',
 'POULTON-LE-FYLDE',
 'PRENTON',
 'PRESCOT',
 'PRESTATYN',
 'PRESTEIGNE',
 'PRESTON',
 'PRINCES RISBOROUGH',
 'PRUDHOE',
 'PUDSEY',
 'PULBOROUGH',
 'PURFLEET',
 'PURFLEET-ON-THAMES',
 'PURLEY',
 'PWLLHELI',
 'QUEENBOROUGH',
 'RADLETT',
 'RADSTOCK',
 'RAINHAM',
 'RAMSGATE',
 'RAYLEIGH',
 'READING',
 'REDCAR',
 'REDDITCH',
 'REDHILL',
 'REDRUTH',
 'REIGATE',
 'RETFORD',
 'RHAYADER',
 'RHOSGOCH',
 'RHOSNEIGR',
 'RHYL',
 'RICHMOND',
 'RICKMANSWORTH',
 'RIDING MILL',
 'RINGWOOD',
 'RIPLEY',
 'RIPON',
 'ROBERTSBRIDGE',
 'ROCHDALE',
 'ROCHESTER',
 'ROCHFORD',
 'ROMFORD',
 'ROMNEY MARSH',
 'ROMSEY',
 'ROSS-ON-WYE',
 'ROSSENDALE',
 'ROTHERHAM',
 "ROWLAND'S CASTLE",
 'ROWLANDS GILL',
 'ROWLEY REGIS',
 'ROYSTON',
 'RUARDEAN',
 'RUGBY',
 'RUGELEY',
 'RUISLIP',
 'RUNCORN',
 'RUSHDEN',
 'RUTHIN',
 'RYDE',
 'RYE',
 'RYTON',
 'SAFFRON WALDEN',
 'SALCOMBE',
 'SALE',
 'SALFORD',
 'SALISBURY',
 'SALTASH',
 'SALTBURN-BY-THE-SEA',
 'SANDBACH',
 'SANDHURST',
 'SANDOWN',
 'SANDWICH',
 'SANDY',
 'SAUNDERSFOOT',
 'SAWBRIDGEWORTH',
 'SAXMUNDHAM',
 'SCARBOROUGH',
 'SCUNTHORPE',
 'SEAFORD',
 'SEAHAM',
 'SEAHOUSES',
 'SEASCALE',
 'SEATON',
 'SEAVIEW',
 'SEDBERGH',
 'SELBY',
 'SETTLE',
 'SEVENOAKS',
 'SHAFTESBURY',
 'SHANKLIN',
 'SHEERNESS',
 'SHEFFIELD',
 'SHEFFORD',
 'SHEPPERTON',
 'SHEPTON MALLET',
 'SHERBORNE',
 'SHERINGHAM',
 'SHIFNAL',
 'SHILDON',
 'SHIPLEY',
 'SHIPSTON-ON-STOUR',
 'SHOREHAM-BY-SEA',
 'SHREWSBURY',
 'SIDCUP',
 'SIDMOUTH',
 'SITTINGBOURNE',
 'SKEGNESS',
 'SKELMERSDALE',
 'SKIPTON',
 'SLEAFORD',
 'SLOUGH',
 'SMETHWICK',
 'SNODLAND',
 'SOLIHULL',
 'SOMERTON',
 'SOUTH BRENT',
 'SOUTH CROYDON',
 'SOUTH MOLTON',
 'SOUTH OCKENDON',
 'SOUTH PETHERTON',
 'SOUTH SHIELDS',
 'SOUTHALL',
 'SOUTHAM',
 'SOUTHAMPTON',
 'SOUTHEND-ON-SEA',
 'SOUTHMINSTER',
 'SOUTHPORT',
 'SOUTHSEA',
 'SOUTHWELL',
 'SOUTHWOLD',
 'SOWERBY BRIDGE',
 'SPALDING',
 'SPENNYMOOR',
 'SPILSBY',
 'ST AGNES',
 'ST ALBANS',
 'ST ASAPH',
 'ST AUSTELL',
 'ST BEES',
 'ST COLUMB',
 'ST HELENS',
 'ST IVES',
 'ST LEONARDS-ON-SEA',
 'ST NEOTS',
 'STAFFORD',
 'STAINES',
 'STAINES-UPON-THAMES',
 'STALYBRIDGE',
 'STAMFORD',
 'STANFORD-LE-HOPE',
 'STANLEY',
 'STANMORE',
 'STANSTED',
 'STEVENAGE',
 'STEYNING',
 'STOCKBRIDGE',
 'STOCKPORT',
 'STOCKSFIELD',
 'STOCKTON-ON-TEES',
 'STOKE-ON-TRENT',
 'STOKE-SUB-HAMDON',
 'STONE',
 'STONEHOUSE',
 'STOURBRIDGE',
 'STOURPORT-ON-SEVERN',
 'STOWMARKET',
 'STRATFORD-UPON-AVON',
 'STREET',
 'STROUD',
 'STUDLEY',
 'STURMINSTER NEWTON',
 'SUDBURY',
 'SUNBURY-ON-THAMES',
 'SUNDERLAND',
 'SURBITON',
 'SUTTON',
 'SUTTON COLDFIELD',
 'SUTTON-IN-ASHFIELD',
 'SWADLINCOTE',
 'SWAFFHAM',
 'SWANAGE',
 'SWANLEY',
 'SWANSCOMBE',
 'SWANSEA',
 'SWINDON',
 'TADCASTER',
 'TADLEY',
 'TADWORTH',
 'TALSARNAU',
 'TALYBONT',
 'TAMWORTH',
 'TARPORLEY',
 'TAUNTON',
 'TAVISTOCK',
 'TEDDINGTON',
 'TEIGNMOUTH',
 'TELFORD',
 'TEMPLECOMBE',
 'TENBURY WELLS',
 'TENBY',
 'TENTERDEN',
 'TETBURY',
 'TEWKESBURY',
 'THAME',
 'THAMES DITTON',
 'THATCHAM',
 'THETFORD',
 'THIRSK',
 'THORNTON HEATH',
 'THORNTON-CLEVELEYS',
 'TIDWORTH',
 'TILBURY',
 'TINTAGEL',
 'TIPTON',
 'TIVERTON',
 'TODMORDEN',
 'TONBRIDGE',
 'TONYPANDY',
 'TORPOINT',
 'TORQUAY',
 'TORRINGTON',
 'TOTLAND BAY',
 'TOTNES',
 'TOWCESTER',
 'TREDEGAR',
 'TREFRIW',
 'TREGARON',
 'TREHARRIS',
 'TREORCHY',
 'TRIMDON STATION',
 'TRING',
 'TROWBRIDGE',
 'TRURO',
 'TUNBRIDGE WELLS',
 'TWICKENHAM',
 'TY CROES',
 'TYN-Y-GONGL',
 'TYWYN',
 'UCKFIELD',
 'ULCEBY',
 'ULVERSTON',
 'UMBERLEIGH',
 'UPMINSTER',
 'USK',
 'UTTOXETER',
 'UXBRIDGE',
 'VENTNOR',
 'VERWOOD',
 'VIRGINIA WATER',
 'WADEBRIDGE',
 'WADHURST',
 'WAKEFIELD',
 'WALLASEY',
 'WALLINGFORD',
 'WALLINGTON',
 'WALLSEND',
 'WALSALL',
 'WALSINGHAM',
 'WALTHAM ABBEY',
 'WALTHAM CROSS',
 'WALTON ON THE NAZE',
 'WALTON-ON-THAMES',
 ...]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299433 entries, 0 to 299432
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Transaction unique identifier  299433 non-null  object
 1   Price                          299433 non-null  int64
 2   Date of Transfer               299433 non-null  object
 3   Postcode                       298991 non-null  string
 4   Property Type                  299433 non-null  string
 5   Old/New                        299433 non-null  string
 6   Duration                       299433 non-null  string
 7   PAON                           299433 non-null  string
 8   SAON                           34769 non-null   string
 9   Street                         294778 non-null  string
 10  Locality                       108165 non-null  string
 11  Town/City                      299433 non-null  string
 12  District                       299433 non-null  string
 13  County                         299433 non-null  string
 14  PPD Category Type              299433 non-null  string
 15  Record Status                  299433 non-null  string
dtypes: int64(1), object(2), string(13)
memory usage: 36.6+ MB

In [8]:
df=df.fillna('')

In [9]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299433 entries, 0 to 299432
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Transaction unique identifier  299433 non-null  object
 1   Price                          299433 non-null  int64
 2   Date of Transfer               299433 non-null  object
 3   Postcode                       299433 non-null  string
 4   Property Type                  299433 non-null  string
 5   Old/New                        299433 non-null  string
 6   Duration                       299433 non-null  string
 7   PAON                           299433 non-null  string
 8   SAON                           299433 non-null  string
 9   Street                         299433 non-null  string
 10  Locality                       299433 non-null  string
 11  Town/City                      299433 non-null  string
 12  District                       299433 non-null  string
 13  County                         299433 non-null  string
 14  PPD Category Type              299433 non-null  string
 15  Record Status                  299433 non-null  string
dtypes: int64(1), object(2), string(13)
memory usage: 36.6+ MB

In [10]:
#df1=df['Postcode']
df['House_Unique']=df['PAON']+' '+df['SAON']+' '+df['Street']+' '+df['Locality']

In [14]:
df['Postcode'].unique()

<StringArray>
['HU15 1FT', 'HU17 9RT', 'HU14 3EZ', 'DN14 7ZL', 'YO16 6AE', 'YO43 4DU',
 'BD18 1LR',   'S3 9DE',  'HD3 3JB',  'HD3 4EP',
 ...
  'WV8 2JP',  'WS7 4UW',  'CW3 9PW', 'ST10 1TN', 'WS13 8TN',  'WV3 9DP',
  'B77 2PB', 'ST14 5AE', 'ST14 5FG', 'ST21 6NY']
Length: 240320, dtype: string

In [ ]:
df['Postcode'].unique()

In [17]:
df[df['Property Type']=='F']

,Transaction unique identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status,House_Unique
0,{DBA933FA-5665-669D-E053-6B04A8C0AD56},232999,2022-01-27 00:00,HU15 1FT,F,N,L,FAIRWAY VIEW,APARTMENT 27,ELLOUGHTON ROAD,,BROUGH,EAST RIDING OF YORKSHIRE,EAST RIDING OF YORKSHIRE,A,A,FAIRWAY VIEW APARTMENT 27 ELLOUGHTON ROAD
53,{DBA933FA-51A9-669D-E053-6B04A8C0AD56},174000,2022-02-11 00:00,LS6 4RQ,F,N,L,40,,STONE MILL COURT,,LEEDS,LEEDS,WEST YORKSHIRE,A,A,40 STONE MILL COURT
55,{DBA933FA-51AF-669D-E053-6B04A8C0AD56},151000,2022-02-21 00:00,HD3 4GF,F,N,L,17,,CHARLES AVENUE,,HUDDERSFIELD,KIRKLEES,WEST YORKSHIRE,A,A,17 CHARLES AVENUE
66,{E53EDD2D-A31C-83EC-E053-6B04A8C03A59},135000,2022-06-22 00:00,CM0 7EG,F,N,L,45,,TATTERSALLS CHASE,,SOUTHMINSTER,MALDON,ESSEX,A,A,45 TATTERSALLS CHASE
71,{DBA933FA-4626-669D-E053-6B04A8C0AD56},154000,2022-01-05 00:00,SN25 1UD,F,N,L,22,,CONNELLY CLOSE,,SWINDON,SWINDON,SWINDON,A,A,22 CONNELLY CLOSE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299335,{DE2D0CE0-1B19-51EE-E053-6C04A8C00671},290000,2022-03-29 00:00,SM6 8TE,F,N,L,17,FLAT 2,BELMONT ROAD,,WALLINGTON,SUTTON,GREATER LONDON,A,A,17 FLAT 2 BELMONT ROAD
299340,{DE2D0CE0-1F7C-51EE-E053-6C04A8C00671},177000,2022-03-25 00:00,IP5 1NF,F,N,L,20A,,GLANVILLE PLACE,KESGRAVE,IPSWICH,EAST SUFFOLK,SUFFOLK,A,A,20A GLANVILLE PLACE KESGRAVE
299395,{DE2D0CE0-12A8-51EE-E053-6C04A8C00671},102000,2022-02-28 00:00,WS13 6XD,F,N,L,HOMELODGE HOUSE,4,CASTLE DYKE,,LICHFIELD,LICHFIELD,STAFFORDSHIRE,A,A,HOMELODGE HOUSE 4 CASTLE DYKE
299405,{DE2D0CE0-1675-51EE-E053-6C04A8C00671},600000,2022-03-11 00:00,DE13 8FN,F,N,L,BARTON MARINA,20 THE LAKESIDE,BARTON TURN,BARTON UNDER NEEDWOOD,BURTON-ON-TRENT,EAST STAFFORDSHIRE,STAFFORDSHIRE,A,A,BARTON MARINA 20 THE LAKESIDE BARTON TURN BART...
299413,{DE2D0CE0-1682-51EE-E053-6C04A8C00671},230000,2022-03-31 00:00,ST16 3XU,F,N,L,ST. GEORGES MANSIONS,83,ST GEORGES PARKWAY,,STAFFORD,STAFFORD,STAFFORDSHIRE,A,A,ST. GEORGES MANSIONS 83 ST GEORGES PARKWAY

In [13]:
df[df['Old/New']=='Y']

,Transaction unique identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status,House_Unique
1290,{DBA933FA-59DB-669D-E053-6B04A8C0AD56},319950,2022-01-14 00:00,WF1 3FG,S,Y,F,5,,CARTWRIGHT DRIVE,,WAKEFIELD,WAKEFIELD,WEST YORKSHIRE,A,A,5 CARTWRIGHT DRIVE
1291,{DBA933FA-59DD-669D-E053-6B04A8C0AD56},330950,2022-01-28 00:00,WF1 3DQ,S,Y,F,47,,BUTLER WAY,,WAKEFIELD,WAKEFIELD,WEST YORKSHIRE,A,A,47 BUTLER WAY
1292,{DBA933FA-59DE-669D-E053-6B04A8C0AD56},253950,2022-02-04 00:00,WF1 3DQ,T,Y,F,51,,BUTLER WAY,,WAKEFIELD,WAKEFIELD,WEST YORKSHIRE,A,A,51 BUTLER WAY
1293,{DBA933FA-59DF-669D-E053-6B04A8C0AD56},284000,2022-02-11 00:00,HX2 9WD,T,Y,F,8,,PARK VIEW,HOLMFIELD,HALIFAX,CALDERDALE,WEST YORKSHIRE,A,A,8 PARK VIEW HOLMFIELD
1294,{DBA933FA-59E3-669D-E053-6B04A8C0AD56},291950,2022-02-18 00:00,WF1 3DQ,T,Y,F,56,,BUTLER WAY,,WAKEFIELD,WAKEFIELD,WEST YORKSHIRE,A,A,56 BUTLER WAY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296801,{E53EDD2E-ADC3-83EC-E053-6B04A8C03A59},105000,2022-05-17 00:00,B70 8ET,O,Y,L,6 VICTORIA COURT,UNIT 2,VICTORIA STREET,,WEST BROMWICH,SANDWELL,WEST MIDLANDS,B,A,6 VICTORIA COURT UNIT 2 VICTORIA STREET
296802,{E53EDD2E-ADC4-83EC-E053-6B04A8C03A59},105000,2022-05-17 00:00,B70 8ET,O,Y,L,6 VICTORIA COURT,UNIT 4,VICTORIA STREET,,WEST BROMWICH,SANDWELL,WEST MIDLANDS,B,A,6 VICTORIA COURT UNIT 4 VICTORIA STREET
296804,{E53EDD2E-ADC6-83EC-E053-6B04A8C03A59},590000,2022-02-25 00:00,B90 8DN,D,Y,F,36,,MAGNOLIA DRIVE,BLYTHE VALLEY PARK,SOLIHULL,SOLIHULL,WEST MIDLANDS,B,A,36 MAGNOLIA DRIVE BLYTHE VALLEY PARK
298441,{DE2D0CE0-0C7F-51EE-E053-6C04A8C00671},460746,2022-03-04 00:00,YO51 9FT,D,Y,F,7,,WHITE CLOSE,LANGTHORPE,YORK,HARROGATE,NORTH YORKSHIRE,A,A,7 WHITE CLOSE LANGTHORPE
298444,{DE2D0CE0-0C84-51EE-E053-6C04A8C00671},597995,2022-04-20 00:00,YO51 9FT,D,Y,F,5,,WHITE CLOSE,LANGTHORPE,YORK,HARROGATE,NORTH YORKSHIRE,A,A,5 WHITE CLOSE LANGTHORPE